export const firstStartedAt = new Date('2026-09-01T12:00:00.000Z');
export const firstLastActivityAt = new Date('2026-09-01T12:03:00.000Z');
export const secondStartedAt = new Date('2026-09-02T12:00:00.000Z');
export const secondLastActivityAt = new Date('2026-09-02T12:01:00.000Z');
export const analyticsInput = {
  owner: { id: 'owner-1', email: 'owner@example.test' },
  visitRows: [
    {
      id: 'visit-1',
      viewerSessionId: 'session-1',
      viewerUserId: null,
      viewerEmail: 'viewer@example.test',
      identityConfidence: 'authenticated' as const,
      startedAt: firstStartedAt,
      lastActivityAt: firstLastActivityAt,
      revisionNumber: 1,
      linkId: 'link-1',
      linkName: 'Customer link',
      senderId: 'sender-1',
      senderEmail: 'sender@example.test',
      totalSlides: 2,
    },
    {
      id: 'visit-2',
      viewerSessionId: 'session-2',
      viewerUserId: null,
      viewerEmail: null,
      identityConfidence: 'anonymous' as const,
      startedAt: secondStartedAt,
      lastActivityAt: secondLastActivityAt,
      revisionNumber: 1,
      linkId: 'link-1',
      linkName: 'Customer link',
      senderId: 'sender-1',
      senderEmail: 'sender@example.test',
      totalSlides: 2,
    },
  ],
  slideRows: [
    {
      id: 'slide-1',
      revisionNumber: 1,
      stableSlideId: 'stable-slide-1',
      ordinal: 1,
      title: 'Introduction',
    },
    {
      id: 'slide-2',
      revisionNumber: 1,
      stableSlideId: 'stable-slide-2',
      ordinal: 2,
      title: 'Details',
    },
  ],
  engagementRows: [
    {
      visitId: 'visit-1',
      id: 'slide-1',
      revisionNumber: 1,
      stableSlideId: 'stable-slide-1',
      ordinal: 1,
      title: 'Introduction',
      activeDurationMs: 100,
      viewCount: 1,
      qualified: true,
      firstSequence: 2,
      lastSequence: 2,
    },
    {
      visitId: 'visit-1',
      id: 'slide-2',
      revisionNumber: 1,
      stableSlideId: 'stable-slide-2',
      ordinal: 2,
      title: 'Details',
      activeDurationMs: 200,
      viewCount: 1,
      qualified: true,
      firstSequence: 1,
      lastSequence: 1,
    },
    {
      visitId: 'visit-2',
      id: 'slide-1',
      revisionNumber: 1,
      stableSlideId: 'stable-slide-1',
      ordinal: 1,
      title: 'Introduction',
      activeDurationMs: 100,
      viewCount: 1,
      qualified: true,
      firstSequence: 1,
      lastSequence: 1,
    },
    {
      visitId: 'missing-visit',
      id: 'slide-1',
      revisionNumber: 1,
      stableSlideId: 'stable-slide-1',
      ordinal: 1,
      title: 'Introduction',
      activeDurationMs: 999,
      viewCount: 1,
      qualified: true,
      firstSequence: 1,
      lastSequence: 1,
    },
  ],
};
